[package]
name = "remark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
function_string_builder = "1.0.3"
regex = "1.10.2"

[dev-dependencies]
unicode-segmentation = "1.10.1"
